# Linear Algebra Week 1 & 2

In [2]:
## import all the modules 

import numpy as np
from numpy import linalg
import math

### 1. Basic Vector Orerations 

In [3]:
# or we can simply use numpy array
v = np.array([1,2,3])           # this is a row vector
w = np.array([4,5,6])           # this is a row vector 
c = 5
print(v,w)

[1 2 3] [4 5 6]


#### Calculate

1. $$
\begin{bmatrix}
    1 \\
    2 \\
    3 
\end{bmatrix}
+
\begin{bmatrix}
    4 \\
    5 \\
    6
\end{bmatrix}
$$
2. $$5*
\begin{bmatrix}
    1 \\
    2 \\
    3 
\end{bmatrix}
$$
3. $$
\begin{bmatrix}
    1 \\
    2 \\
    3 
\end{bmatrix}
*
\begin{bmatrix}
    4 \\
    5 \\
    6
\end{bmatrix}
$$
4. $$
\begin{bmatrix}
    1 \\
    2 \\
    3 
\end{bmatrix}
.dot(
\begin{bmatrix}
    4 \\
    5 \\
    6
\end{bmatrix})
$$

In [4]:
# operations 
rSum = w+v
rProduct = 5*w
rProduct_p = w*v
rProduct_v = w.dot(v)

print ('Sum = ',rSum)
print ('Product 5*w = ',rProduct)
print ('Parall Product w*v= ',rProduct_p)
print ('Vector Product w.dot(v)= ',rProduct_v)

Sum =  [5 7 9]
Product 5*w =  [20 25 30]
Parall Product w*v=  [ 4 10 18]
Vector Product w.dot(v)=  32


### 2. Linear Transformation

- #### Rotate Vector 
    - roateing a vector is a linear transformation. It does not metter you add first or rotate first. 
    <img src="pic/1_rotate_vector.PNG">

   - #### Linear transformation: Some typical questions that we are interested in:
       - Given vector $y \in \mathbf{R}$, find x $x$ such that $f(x) = y$
       - Find scalar $\lambda$ and vector x such that $f(x) = \lambda x$   --   (find engineer value and eigineer vector)

- #### Defination of Linear transformation:
A vector function $f : \mathbf{R}^n \rightarrow \mathbf{R}^m$ is a linear transformation if for all scalars $\alpha$ and for all vectors $x;y \in \mathbf{R}^m$ it is that case that:

    - f (ax) = af (x) and
    - f (x+y) = f (x)+ f (y).
    
    If there is even one scalar $\alpha$ and vector $x \in \mathbf{R}^n$ such that $f(\alpha x) \neq \alpha f(x)$ or if there is even one pair of vectors $x;y \in \mathbf{R}^n$ such that $f(x+y) \neq f(x)+f(y)$, then the vector function f is not a linear transformation.

    Thus, in order to show that a vector function $f$ is not a linear transformation, it suffices to find one such counter example.

- #### Alternative Defination of Linear transformation:
    $L :  \mathbf{R}^n \rightarrow \mathbf{R}^m is a linear transformation if and only if (iff) for all u,v \in \mathbf{R}^n and \alpha,\beta \in \mathbf{R}^n$ $$L(\alpha u+\beta v) = \alpha L(u)+\beta L(v)$$
    
    - $Let v_0, v_1,....,v_{k-1} \in \mathbf{R} and let L :  \mathbf{R}^n \rightarrow \mathbf{R}^m be a linear transformation then:$ $$L(v_0 + v_1 + ... + v_{k-1}) = L(v_0)+L(v_1)+...+L(v_{k-1})$$

### 2.1 Linear Transformation Matrix Representation

$Let v_0, v_1,....,v_{n-1} \in \mathbf{R}, \alpha_0, \alpha_1 ..., \alpha_{n-1} \in \mathbf{R} and let L :  \mathbf{R}^n \rightarrow \mathbf{R}^m be a linear transformation then:$ $$L(\alpha_0 v_0 + \alpha_1 v_1 + ... +\alpha_{n-1} v_{n-1}) = \alpha_0L(v_0)+\alpha_1L(v_1)+...+\alpha_{n-1}L(v_{k-1})$$
A more concise notation:
$$L(\sum_{j=0}^{k-1}\alpha_jv_j)= \sum_{j=0}^{k=1}\alpha_jL(v_j)$$

#### Sample question:
<img src="pic/2_linear_transformation.png" height="500" width="500">

- ### Using Matrix to represent linear transformation
<img src="pic/2_1.PNG">
<img src="pic/2_2.PNG">

### This is so important. Matrix A stroed all the information of linear transformation L(x). L(x) = Ax. 
### This is prety much the definiation of Matrix and Vector multiplication. It is a linear transformation of vector x. 

- Sample question: Matrix, vector multiplications:
$$
y = Ax \text{ when A =} 
\begin{bmatrix}
    -1 &0& 2 \\
    -3 &1& -1\\
    -2 &-1& 2 
\end{bmatrix} \text{ and } 
x = 
\begin{bmatrix}
    1\\
    0\\
    0 
\end{bmatrix} \text{, y = ?}
$$

In [14]:
# or we can simply use numpy array
A = np.array([[-1,0,2],
            [-3,1,-1],
            [-2,-1,2]])           # this is a row vector
x = np.array([1,0,0])
res = A.dot(x)
print("A = ",A)
print("x = ",x)
print("A.dot(x) = ",res)

A =  [[-1  0  2]
 [-3  1 -1]
 [-2 -1  2]]
x =  [1 0 0]
A.dot(x) =  [-1 -3 -2]


### 2.2 Linear Transformation and Rotation

<img src="pic/2_3.PNG">
<img src="pic/2_4.PNG">

### 3 Euclidean length
#### - Defination: $\| a \| = \sqrt{a_{0}^{2} + a_{1}^{2} + ... + a_{n-1}^{2}}$, where a is a vector with n elements in it. 

In [6]:
## Euclidean length of v:
eu_len_v = np.sqrt(v.dot(v))       # we can write out the calculation by ourselves
eu_len_v = np.linalg.norm(v)       # or we can juse linalg in numpy library 

print ('The Euclidean lenght of v is:',eu_len_v)

The Euclidean lenght of v is: 3.74165738677


#### 3.1 Cauchy-Schwarz inequality:
##### - Defination: $\| u \cdot v \| \leq \| u\|\|v\|$,  $\| u \cdot v \| = \| u\|\|v\|$ only if when u and v are colinear. -- which means u and v are parellel. 
#### 3.2 Triangle inequality:
#### - Defination: $ \|z\| = \| u + v \| \leq \| u\|+\|v\|$
<img src="pic/1_21.PNG" height="30%" width="30%">


#### 3.3 Inner products and angle
- let vector $a,b \in \mathbf{R}^n$:
<img src="pic/1_22.PNG" height="60%" width="60%">
- Law of cosin : $\| a - b \|^2 = \| a \|^2 + \|b\|^2 -2\|a\|\|b\|cos \theta$
- $cos \theta = \frac {a \cdot b}{\|a\|\|b\|}$ 

#### some properties:
- when $a \cdot b = 0 $  --- $cos \theta = 0, \theta = \pi/2$ -- so a and b are orthogonal  

#### Calculate it in python 

In [7]:
innerProduct = v.dot(w)
v_norm = np.linalg.norm(v)
w_norm = np.linalg.norm(w)
cos_theta = innerProduct/(v_norm*w_norm)                 # property of cos theta
angle = np.arccos(cos_theta)/math.pi*180                 # transform the angle to degree
print ('inner product = ',innerProduct)
print ('angle = ' ,angle)

inner product =  32
angle =  12.9331544919
