In [2]:
import numpy as np
import scipy


In [3]:
A = np.array([[1,0,1/3],
    [0,1,-1/4]])


In [5]:
A

array([[ 1.        ,  0.        ,  0.33333333],
       [ 0.        ,  1.        , -0.25      ]])

In [7]:
r = np.array([6,2,3])

In [8]:
np.dot(A,r)

array([7.  , 1.25])

In [9]:
R = np.array([[5,-1,-3,7],[4,-4,1,-2],[9,3,0,12]])


In [10]:
np.dot(A,R)

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])

In [11]:
A@R

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])

In [27]:
T = np.array([[1,0],[2,-1]])

In [28]:
C = np.array([[1,0],[1,1]])

In [29]:
def calculate(T,C):
    inv_C = np.linalg.inv(C)
    D = inv_C.dot(T).dot(C)
    return D 

In [30]:
D = calculate(T,C)
D

array([[ 1.,  0.],
       [ 0., -1.]])

In [35]:
a = np.array([[7,1],[-3,0]])

In [36]:
b = np.array([[-1,0],[0,8]])

In [37]:
c = np.array([[0,-1/3],[1,7/3]])

In [38]:
a.dot(b).dot(c)

array([[ 8., 21.],
       [ 0., -1.]])

In [73]:
A = np.array([[4,-5,6],[7,-8,6],[3/2,-1/2,-2]])

In [74]:
vals, vecs = np.linalg.eig(A)

In [75]:
vecs

array([[-0.6882472 , -0.66666667,  0.40824829],
       [-0.6882472 , -0.66666667, -0.40824829],
       [-0.22941573,  0.33333333, -0.81649658]])

In [42]:
1/np.sqrt(6)

0.4082482904638631

In [47]:
1/np.sqrt(9)

0.3333333333333333

In [56]:
L = np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]])

In [57]:
vals, vecs = np.linalg.eig(L)

In [58]:
vecs

array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.70710678, -0.70710678],
       [ 0.        , -0.        ,  0.70710678,  0.70710678]])

In [59]:
vals

array([ 1., -1.,  1., -1.])

In [64]:
d = 0.8 # Feel free to play with this parameter after running the code once.
M = d * L + (1-d)/4 * np.ones([4, 4]) # np.ones() is the J matrix, with ones for each entry.

In [65]:
vals, vecs = np.linalg.eig(M)

In [66]:
vals

array([-0.8,  0.8,  1. , -0.8])

In [67]:
vecs

array([[ 7.07106781e-01, -5.00000000e-01, -5.00000000e-01,
         1.38504043e-02],
       [-7.07106781e-01, -5.00000000e-01, -5.00000000e-01,
        -1.38504043e-02],
       [ 9.13442977e-18,  5.00000000e-01, -5.00000000e-01,
        -7.06971121e-01],
       [-8.70413704e-18,  5.00000000e-01, -5.00000000e-01,
         7.06971121e-01]])

In [68]:
M

array([[0.05, 0.85, 0.05, 0.05],
       [0.85, 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.85],
       [0.05, 0.05, 0.85, 0.05]])

In [76]:
A = np.array([[3/2,-1],[-1/2,1/2]])

In [77]:
vals, vecs = np.linalg.eig(A)

In [78]:
vals

array([1.8660254, 0.1339746])

In [79]:
vecs

array([[ 0.9390708 ,  0.59069049],
       [-0.34372377,  0.80689822]])

In [81]:
vecs@vals@np.linalg.inv(vecs)

array([ 1.34736065, -1.64725428])