In [2]:
import numpy as np


In [3]:
A = np.array([[1,0,1/3],
    [0,1,-1/4]])


In [5]:
A

array([[ 1.        ,  0.        ,  0.33333333],
       [ 0.        ,  1.        , -0.25      ]])

In [7]:
r = np.array([6,2,3])

In [8]:
np.dot(A,r)

array([7.  , 1.25])

In [9]:
R = np.array([[5,-1,-3,7],[4,-4,1,-2],[9,3,0,12]])


In [10]:
np.dot(A,R)

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])

In [11]:
A@R

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])